version: '3'
services:

  proxy:
    build:
      context: ./traefik
    image: ${REGISTRY}/hub_docker_proxy

  fedora_hub_base:
    build:
      context: ./fedora_hub_base
      args:
        - MINICONDA_VERSION=${MINICONDA_VERSION}
        - NFS_SERVER=${NFS_SERVER}
    image: ${REGISTRY}/fedora_hub_base

  rstudio:
    build:
      context: ./rstudio
      args:
        - REGISTRY=${REGISTRY}
        - R_VERSION=${R_VERSION}
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: ${REGISTRY}/hub_docker_rstudio
    depends_on:
      - fedora_hub_base

  jupyterhub:
    build:
      context: ./jupyterhub
      args:
        - REGISTRY=${REGISTRY}
    image: ${REGISTRY}/hub_docker_jupyterhub
    depends_on:
      - fedora_hub_base

  nfs:
    build:
      context: ./nfs
    image: ${REGISTRY}/nfs-server-alpine:12
